appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IhdybR1E3UkiZ6o0SlLRc6jI11zt+8HgPjBSvXXUtLNOsmWVeaP7UVsa1SX4IhftnYsQYqVPZkgLZDDR1AiRXoBxyp0tg23AXNaqj1rV0t7FSMHMnqOYXek+xPu/RY9ygo8zdvaWDq1AV6a1iN/8w1amvnXl8b8RC9THyR4BqSkhzEAYwj9Pw9nd/f44gK8bF7f3pA0/M07D04kmnWKJaTw+0hwBFwFRPJ/yiWQYzR370t8lc1Xlg1UAGgGTw9mfVd1FAyvq4TgHq+x2qpLqJ6WDKjXsKnbBM3VjC+00j5LYik8PYOqI7GvBZ71+SSD8PvOCEExcX4XRYfcO9bcP6fWoHKU3tfF2DRf4wcVDnT9nQlz2Iox2WhbxhV69PyHH+5o73S43OoPb8zvMIxvJna5RrCuQtJe9iQgTCuZ6Qg1RjK1fUwbUBMPioC/2w2md2PVd6Rzfbk53Hx0zgFka/jRYQFX6JyXhfQhJrisylUQexHs3uEFjPPSNl747b68Nw6DgWcQTkiuNLxTjD9rA7yiPdD7Y49jHZ+l2yGn0vWYZ4UwHNxYCsx3vABoRmr8LqQLeK9t1+lQgrz4h3qUwowCsjpMf5If6qSKPhZ3jqN8p++2GDzJIxGWXR9n0ruplo4k8nOBazC33vZ4hxDIoMGsJB4nQ4KvFCkVrvsG8PXE=}
provider:
  win: azure
conda_forge_output_validation: true
